### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by sharksforarms**
Some clippy/rust 2018/cleanup

### CODE REVIEW

**Comment by sharksforarms** [comment]
Hey @chifflier any chance this could get merged? This is just some aesthetics to update to rust 2018 and formatting the code using rustfmt as well as updating the dependencies! Looking forward to contribute more.

**Comment by chifflier** [comment]
Sorry I forgot about that. I'll have a look ASAP

**Comment by sharksforarms** [comment]
Cool let me know if it needs changes!

**Comment by steven-joruk** [comment]
Hi @chifflier, please can you merge this? I'd like to contribute but the reformatting of this would cause lots of conflicts in future work.

**Comment by chifflier** [comment]
Merged, thanks!
I also upgraded dependencies and fix a new clippy warning.

**Pull request merged**
